export const adminSushiProductFields = [
  "id",
  "title",
  "handle",
  "description",
  "thumbnail",
  "images.id",
  "images.url",
  "images.rank",
  "status",
  "metadata",
  "variants.id",
  "variants.sku",
  "variants.title",
  "variants.manage_inventory",
  "variants.prices.amount",
  "variants.prices.id",
  "variants.inventory_quantity",
] as const
